# Generated by Django 5.0.4 on 2024-11-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedIndustryByAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_app.industryregister')),
            ],
        ),
    ]
