# Generated by Django 5.0.4 on 2024-11-16 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new_app.industryregister'),
        ),
    ]
