# Generated by Django 5.0.4 on 2024-10-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_consumerregister_industryregister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerregister',
            name='address',
        ),
    ]
