# Generated by Django 5.0.4 on 2024-11-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_alter_meeting_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
