# Generated by Django 5.0.4 on 2024-10-31 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_complaintresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
