# Generated by Django 5.0.4 on 2024-11-03 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_approvedindustrybyadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_app.industryregister')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=False)),
                ('industry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='new_app.industryregister')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
