# Generated by Django 5.0.4 on 2024-10-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IndustryProfile',
        ),
    ]
