# Generated by Django 5.0.4 on 2024-11-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_industryapproval_industrylogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industrylogin',
            name='industry',
        ),
    ]
