# Generated by Django 5.0.4 on 2024-10-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_remove_consumerregister_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
