# Generated by Django 5.0.4 on 2024-10-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_login_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
