# Generated by Django 5.0.4 on 2024-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_complaint_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerregister',
            name='zip_code',
            field=models.CharField(max_length=6),
        ),
    ]
