# Generated by Django 5.0.4 on 2024-11-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_remove_industrylogin_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='industryapproval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='industryapproval',
            name='industry',
        ),
        migrations.DeleteModel(
            name='IndustryLogin',
        ),
        migrations.DeleteModel(
            name='IndustryApproval',
        ),
    ]
