# Generated by Django 5.0.4 on 2024-11-03 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_remove_industryapproval_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
