# Generated by Django 5.0.4 on 2024-11-25 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_alter_consumerregister_zip_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoTutorial',
        ),
    ]
