# Generated by Django 5.0.4 on 2024-10-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_industryprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='has_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
